Introduce the snapshot command for ynh-dev

diff --git a/ynh-dev b/ynh-dev
--- a/ynh-dev
+++ b/ynh-dev
@@ -2,16 +2,23 @@
 
 # shellcheck disable=SC2155,SC2034,SC2164
 
+DEFAULT_DIST=bookworm
+
 function show_usage() {
     cat <<EOF
 
   ${BLUE}On the host, to manage boxes${NORMAL}
   ${BLUE}============================${NORMAL}
 
-  start [DIST] [NAME] [YNH_BRANCH]   (Create and) starts a box (DIST=bookworm, NAME=ynh-dev and YNH_BRANCH=unstable by default)
-  attach [DIST] [NAME] [YNH_BRANCH] Attach an already started box (DIST=bookworm, NAME=ynh-dev and YNH_BRANCH=unstable by default)
-  destroy [DIST] [NAME] [YNH_BRANCH] Destroy the ynh-dev box (DIST=bookworm, NAME=ynh-dev and YNH_BRANCH=unstable by default)
-  rebuild [DIST] [NAME] [YNH_BRANCH] Rebuild a fresh, up-to-date box (DIST=bookworm, NAME=ynh-dev and YNH_BRANCH=unstable by default)
+  start [DIST] [NAME] [YNH_BRANCH]   (Create and) starts a box (DIST=$DEFAULT_DIST, NAME=ynh-dev and YNH_BRANCH=unstable by default)
+  attach [DIST] [NAME] [YNH_BRANCH]  Attach an already started box (DIST=$DEFAULT_DIST, NAME=ynh-dev and YNH_BRANCH=unstable by default)
+  destroy [DIST] [NAME] [YNH_BRANCH] Destroy the ynh-dev box (DIST=$DEFAULT_DIST, NAME=ynh-dev and YNH_BRANCH=unstable by default)
+  rebuild [DIST] [NAME] [YNH_BRANCH] Rebuild a fresh, up-to-date box (DIST=$DEFAULT_DIST, NAME=ynh-dev and YNH_BRANCH=unstable by default)
+  snapshot [-d|--dist=DEBIAN_DISTRO] [-n|--name=NAME] [-b|--branch=(stable|testing|unstable)] [-h|--help]
+      create                         Create a new snapshot of the container
+      list                           List snapshots
+      delete                         Delete a snapshot
+      restore                        Restore a snapshot
 
   ${BLUE}Inside the dev instance${NORMAL}
   ${BLUE}=======================${NORMAL}
@@ -58,6 +65,7 @@ function main()
         test|--test)               run_tests      "${ARGUMENTS[@]}" ;;
 
         catalog|--catalog)         catalog        "${ARGUMENTS[@]}" ;;
+        snapshot|--snapshot)       snapshot       "${ARGUMENTS[@]}" ;;
 
         rebuild-api-doc|--rebuild-api-doc)   rebuild_api_doc   "${ARGUMENTS[@]}" ;;
 
@@ -83,33 +91,33 @@ readonly WHITE=$(printf '\033[39m')
 
 function success()
 {
-  local msg=${1}
-  echo "[${BOLD}${GREEN} OK ${NORMAL}] ${msg}"
+    local msg=${1}
+    echo "[${BOLD}${GREEN} OK ${NORMAL}] ${msg}"
 }
 
 function info()
 {
-  local msg=${1}
-  echo "[${BOLD}${BLUE}INFO${NORMAL}] ${msg}"
+    local msg=${1}
+    echo "[${BOLD}${BLUE}INFO${NORMAL}] ${msg}"
 }
 
 function warn()
 {
-  local msg=${1}
-  echo "[${BOLD}${ORANGE}WARN${NORMAL}] ${msg}" 2>&1
+    local msg=${1}
+    echo "[${BOLD}${ORANGE}WARN${NORMAL}] ${msg}" 2>&1
 }
 
 function error()
 {
-  local msg=${1}
-  echo "[${BOLD}${RED}FAIL${NORMAL}] ${msg}"  2>&1
+    local msg=${1}
+    echo "[${BOLD}${RED}FAIL${NORMAL}] ${msg}"  2>&1
 }
 
 function critical()
 {
-  local msg=${1}
-  echo "[${BOLD}${RED}CRIT${NORMAL}] ${msg}"  2>&1
-  exit 1
+    local msg=${1}
+    echo "[${BOLD}${RED}CRIT${NORMAL}] ${msg}"  2>&1
+    exit 1
 }
 
 function assert_inside_vm() {
@@ -155,6 +163,50 @@ function prepare_cache_and_deps() {
     info "Installing dependencies ... (this may take a while)"
     yarn install --frozen-lockfile
     popd
+}
+
+function container_info_opts() {
+    local params="$(getopt -o hn:d:b: -l help,name:,dist:,branch: --name "container info options" -- "$@")"
+
+    # NB: the `set` command redefines the positional arguments (aka $@).
+    eval set -- "$params"
+
+    HELP=false
+    while true
+    do
+            case "$1" in
+                -h|--help)
+                    HELP=true
+                    shift
+                    break
+                    ;;
+                -n|--name)
+                    NAME=$2
+                    shift 2
+                    ;;
+                -d|--dist)
+                    DIST=$2
+                    shift 2
+                    ;;
+                -b|--branch)
+                    YNH_BRANCH=$2
+                    shift 2
+                    ;;
+                --)
+                    shift
+                    break
+                    ;;
+                -*)
+                    echo "Not implemented: $1" >&2
+                    exit 1
+                    ;;
+                *)
+                    break
+                    ;;
+            esac
+        done
+    BOX="${NAME:-ynh-dev}-${DIST:-$DEFAULT_DIST}-${YNH_BRANCH:-unstable}"
+    REST="$*"
 }
 
 ##################################################################
@@ -640,6 +692,109 @@ function rebuild_api_doc()
     info "Rebuild swagger json/js according to actionsmap"
     python3 generate_api_doc.py
     success "You should now open yunohost/doc/api.html using your favorite browser"
+}
+
+function snapshot()
+{
+    check_incus_setup
+    local HELP
+    local DIST
+    local NAME
+    local YNH_BRANCH
+    local BOX
+    local REST
+    case "${1:-}" in
+        -*)
+            container_info_opts "$@"
+            eval set -- "$REST"
+            ACTION="${1:-}"
+            shift 1
+            ;;
+        *)
+            ACTION="${1:-}"
+            shift 1
+            container_info_opts "$@"
+            eval set -- "$REST"
+            ;;
+    esac
+
+    if [ -z "$ACTION" ] || [ "$ACTION" == "--" ]; then
+        if "$HELP" ; then
+            info "List of possible commands with snapshot:"
+            info ""
+            info "$ $0 snapshot list"
+            "$0" snapshot list --help
+            info ""
+            info "$ $0 snapshot create"
+            "$0" snapshot create --help
+            info ""
+            info "$ $0 snapshot delete"
+            "$0" snapshot delete --help
+            info ""
+            info "$ $0 snapshot restore"
+            "$0" snapshot restore --help
+            exit 0
+        fi
+        critical "one of these action required: create, list, delete or restore"
+    fi
+    local SNAPSHOT
+    get_snapshot_name() {
+        [ "$#" -eq 1 ] || critical "expected exactly one positional argument"
+        echo "$1"
+    }
+
+    case "${ACTION}" in
+        list)
+            if "$HELP"; then
+                info "List the snapshots available for restoration"
+                info "Usage: $0 snapshot list [-d|--dist=DIST] [-n|--name=NAME] [-b|--branch=BRANCH]"
+                exit 0
+            fi
+
+            info "The following snapshots are available for $NAME (incus container name: $BOX)"
+            incus snapshot list "$BOX"
+            ;;
+        create)
+            if "$HELP"; then
+                info "Create a new snapshot"
+                info "Usage: $0 snapshot create [-d|--dist=DIST] [-n|--name=NAME] [-b|--branch=BRANCH] SNAPSHOT_NAME"
+                exit 0
+            fi
+
+            SNAPSHOT=$(get_snapshot_name "$@")
+            if incus snapshot create "$BOX" "$SNAPSHOT"; then
+                success "✨ Snapshot \"$SNAPSHOT\" created for $NAME"
+            fi
+            ;;
+        delete)
+            if "$HELP"; then
+                info "Delete a snapshot"
+                info "Usage: $0 snapshot delete [-d|--dist=DIST] [-n|--name=NAME] [-b|--branch=BRANCH] SNAPSHOT_NAME"
+                exit 0
+            fi
+
+            SNAPSHOT=$(get_snapshot_name "$@")
+            info "Deleting snapshot $SNAPSHOT"
+            if incus snapshot delete "$BOX" "$SNAPSHOT"; then
+                success "💥 Snapshot \"$SNAPSHOT\" deleted for $NAME"
+            fi
+            ;;
+        restore)
+            if "$HELP"; then
+                info "Restore a snapshot"
+                info "Usage: $0 snapshot restore [-d|--dist=DIST] [-n|--name=NAME] [-b|--branch=BRANCH] SNAPSHOT_NAME"
+                exit 0
+            fi
+
+            SNAPSHOT=$(get_snapshot_name "$@")
+            if incus snapshot restore "$BOX" "$SNAPSHOT"; then
+                success "♻️ Snapshot \"$SNAPSHOT\" restored for $NAME"
+            fi
+            ;;
+        *)
+            critical "Unknown snapshot action '${ACTION}'."
+            ;;
+    esac
 }
 
 main "$@"
